version: 2.1

jobs:
  release:
    working_directory: /go/src/github.com/10380r/generate-release-note
    docker:
      - image: circleci/golang:1.16.0
    steps:
      - checkout
      - run:
          name: Install ghch and github-release
          command: |
            go install github.com/Songmu/ghch/cmd/ghch@v0.10.2
            go install github.com/github-release/github-release@v0.10.0
      - run:
          name: Create release note
          command: |
            github-release release \
              --user 10380r \
              --repo generate-release-note \
              --tag "${CIRCLE_TAG}" \
              --name "${CIRCLE_TAG}" \
              --description "$(ghch --format=markdown --latest)"

workflows:
  workflow:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
